# Generated by Django 4.1.7 on 2023-03-04 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0002_house_room_user_rename_member_device_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='deviceName',
            new_name='device_name',
        ),
        migrations.RenameField(
            model_name='house',
            old_name='houseName',
            new_name='house_name',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='roomNaem',
            new_name='room_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='fullName',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='phoneNumber',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='userName',
            new_name='user_name',
        ),
    ]
