# Generated by Django 4.1.7 on 2023-03-05 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0004_house_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='room',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='house.room'),
        ),
        migrations.AddField(
            model_name='room',
            name='house',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='house.house'),
        ),
    ]
