# Generated by Django 4.1.7 on 2023-10-03 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("house", "0005_device_room_room_house"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sensor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_id", models.CharField(max_length=255)),
                ("device_name", models.CharField(max_length=255)),
                ("value", models.CharField(max_length=255)),
                ("unit", models.CharField(max_length=255)),
                ("time", models.CharField(max_length=255)),
                (
                    "house",
                    models.ForeignKey(
                        default=0,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="house.house",
                    ),
                ),
            ],
        ),
    ]
