# Generated by Django 4.1.7 on 2023-10-03 07:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("house", "0006_sensor"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sensor",
            old_name="device_id",
            new_name="sensor_id",
        ),
        migrations.RenameField(
            model_name="sensor",
            old_name="device_name",
            new_name="sensor_name",
        ),
    ]
