# Generated by Django 4.1.7 on 2023-10-23 06:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("house", "0007_rename_device_id_sensor_sensor_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="house",
            name="status",
            field=models.BooleanField(default=True, max_length=255),
        ),
    ]
